on: [push]

name: Build_And_Deploy_Workflow

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout Github Action"
        uses: actions/checkout@master
      - run: docker build . -t chapadany.azurecr.io/point-of-sale-api:${{ github.sha }}

      - uses: azure/docker-login@v1
        with:
          login-server: chapadany.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - run: docker push chapadany.azurecr.io/point-of-sale-api:${{ github.sha }}

  deploy-test:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_TEST_CREDENTIALS }}

      - name: "Change webapp version"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "test-chapadany-web"
          images: "chapadany.azurecr.io/point-of-sale-api:${{ github.sha }}"

      - name: Azure logout
        run: |
          az logout
