on: [workflow_dispatch]

name: Deploy_Prod

jobs:

  deploy-prod:
    runs-on: ubuntu-latest

    steps:

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_TEST_CREDENTIALS }}

      - name: "Change webapp version"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "chapadany-api"
          images: "chapadany.azurecr.io/point-of-sale-api:${{ github.sha }}"

      - name: Azure logout
        run: |
          az logout
